import fs from 'fs';
import { run } from './adv.mjs';
const S = process.argv[2];
const base = fs.readFileSync(S + '/korean.pdf');
const mod = fs.readFileSync(S + '/pdf/modern.pdf');
console.log('1회차 — 손상된 파일');
await run('빈 파일', Buffer.alloc(0));
await run('널 1KB', Buffer.alloc(1024));
await run('머리글만', Buffer.from('%PDF-1.7\n'));
await run('앞 절반', base.subarray(0, base.length >> 1));
await run('뒤 절반', base.subarray(base.length >> 1));
await run('꼬리 잘림(트레일러X)', base.subarray(0, base.length - 200));
const b1 = Buffer.from(base); for (let i = 0; i < b1.length; i += 97) b1[i] ^= 0xff;
await run('1% 바이트 뒤집기', b1);
const b2 = Buffer.from(base); b2.write('%PDF-9.9', 0);
await run('버전 이상', b2);
const b3 = Buffer.from(base.toString('latin1').replace(/\/Length (\d+)/g, '/Length 999999999'), 'latin1');
await run('Length 거대', b3);
const b4 = Buffer.from(base.toString('latin1').replace(/\/Length1 \d+/g, '/Length1 4294967295'), 'latin1');
await run('Length1 거대', b4);
const b5 = Buffer.from(base.toString('latin1').replace(/\/Length (\d+)/g, '/Length 0'), 'latin1');
await run('Length 0', b5);
const b6 = Buffer.from(base.toString('latin1').replace(/(\d+) 0 R/g, '999999 0 R'), 'latin1');
await run('참조 전부 없는 객체', b6);
const b7 = Buffer.from(base.toString('latin1').replace('/DescendantFonts [13 0 R]', '/DescendantFonts [5 0 R]'), 'latin1');
await run('자손 글꼴 자기참조', b7);
const b8 = Buffer.from(mod.toString('latin1').replace(/\/Parent 2 0 R/g, '/Parent 1 0 R'), 'latin1');
await run('페이지 트리 순환', b8);
await run('PDF 아닌 JPEG', fs.readFileSync(S + '/pdf/scanned.pdf').subarray(0, 3000));
const b9 = Buffer.concat([base, base]);
await run('두 번 이어붙임', b9);
